package com.jordanbunke.stipple_effect.utility;

public class IconCodes {
    public static final String
            PROGRAM = "program_icon",
            NEW_PROJECT = "new_project",
            OPEN_FILE = "open_file",
            CLOSE_PROJECT = "close_project",
            SAVE = "save",
            SAVE_AS = "save_as",
            RESIZE = "resize",
            PAD = "pad",
            PREVIEW = "preview",
            UNDO = "undo",
            GRANULAR_UNDO = "granular_undo",
            GRANULAR_REDO = "granular_redo",
            REDO = "redo",
            NEW_FRAME = "new_frame",
            DUPLICATE_FRAME = "duplicate_frame",
            REMOVE_FRAME = "remove_frame",
            MOVE_FRAME_FORWARD = "move_frame_forward",
            MOVE_FRAME_BACK = "move_frame_back",
            TO_FIRST_FRAME = "to_first_frame",
            PREVIOUS = "previous",
            NEXT = "next",
            TO_LAST_FRAME = "to_last_frame",
            PLAY = "play",
            STOP = "stop",
            LOOP = "loop",
            FORWARDS = "forwards",
            BACKWARDS = "backwards",
            PONG = "pong",
            NEW_LAYER = "new_layer",
            DUPLICATE_LAYER = "duplicate_layer",
            REMOVE_LAYER = "remove_layer",
            MOVE_LAYER_UP = "move_layer_up",
            MOVE_LAYER_DOWN = "move_layer_down",
            MERGE_WITH_LAYER_BELOW = "merge_with_layer_below",
            ENABLE_ALL_LAYERS = "enable_all_layers",
            LAYER_ENABLED = "layer_enabled",
            LAYER_DISABLED = "layer_disabled",
            ISOLATE_LAYER = "isolate_layer",
            ONION_SKIN_NONE = "onion_skin_none",
            ONION_SKIN_PREVIOUS = "onion_skin_previous",
            ONION_SKIN_NEXT = "onion_skin_next",
            ONION_SKIN_BOTH = "onion_skin_both",
            FRAMES_LINKED = "frames_linked",
            FRAMES_UNLINKED = "frames_unlinked",
            LAYER_SETTINGS = "layer_settings",
            SWAP_COLORS = "swap_colors",
            DECREMENT = "decrement",
            INCREMENT = "increment",
            OUTLINE = "outline",
            VERTICAL_REFLECTION = "vertical_reflection",
            HORIZONTAL_REFLECTION = "horizontal_reflection",
            INCLUDED = "included",
            EXCLUDED = "excluded",
            SETTINGS = "settings",
            BULLET_POINT = "bullet_point",
            INFO = "info";

    public static final String NO_ICON_PREFIX = "__";

    public static final String
            GENERAL = NO_ICON_PREFIX + "general",
            CLIPBOARD_SHORTCUTS = NO_ICON_PREFIX + "clipboard_shortcuts",
            SELECTION_SHORTCUTS = NO_ICON_PREFIX + "selection_shortcuts",
            COLOR_SHORTCUTS = NO_ICON_PREFIX + "color_shortcuts",
            PLAYBACK_MODES = NO_ICON_PREFIX + "playback",
            LAYER_VISIBILITY = NO_ICON_PREFIX + "visibility",
            ONION_SKIN = NO_ICON_PREFIX + "onion_skin",
            FRAME_LOCKING = NO_ICON_PREFIX + "frame_locking";
}
